# Generated by Django 4.0.3 on 2022-04-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Как к тебе обращаться?')),
                ('anons', models.CharField(max_length=250, verbose_name='Тема послания...')),
                ('full_text', models.TextField(verbose_name='Отзывы, предложения о сотрудничестве и конструктивную критику приветствуем!')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Если ждёшь ответ, оставляй почту')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
    ]
